apiVersion: v1
kind: ConfigMap
metadata:
  name: kutt-config
data:
  .env:  |
    
    SITE_NAME: Kutt
    DEFAULT_DOMAIN: http://localhost
    LINK_LENGTH: 6
    DB_HOST: postgres
    DB_PORT: 5432
    DB_USER: user
    DB_SSL: false
    # NEO4J_DB_URI: bolt://localhost
    # NEO4J_DB_USERNAME: neo4j
    # NEO4J_DB_PASSWORD: pass
    
    REDIS_PORT: 6379 
    DISALLOW_REGISTRATION: false
    DISALLOW_ANONYMOUS_LINKS: false
    POSTGRES_USER: user
    POSTGRES_DB: kutt

    # The daily limit for each user
    USER_LIMIT_PER_DAY: 50

    NON_USER_COOLDOWN: 0

    # Max number of visits for each link to have detailed stats
    DEFAULT_MAX_STATS_PER_LINK: 5000

    # Use HTTPS for links with custom domain
    CUSTOM_DOMAIN_USE_HTTPS: false

    # A passphrase to encrypt JWT. Use a long and secure key.
    JWT_SECRET: securekey

    # Admin emails so they can access admin actions on settings page
    # Comma seperated
    # ADMIN_EMAILS:
    # Your email host details to use to send verification emails.
    # More info on http://nodemailer.com/
    # Mail from example "Kutt <support@kutt.it>". Leave empty to use MAIL_USER
    MAIL_HOST: 0.0.0.0
    MAIL_PORT: 25
    MAIL_SECURE: true
    MAIL_USER: k8s@mail.kutt
    # MAIL_FROM:
    MAIL_PASSWORD: admin 

    # Support email to show on the app
    CONTACT_EMAIL: annuore@gmail
  POSTGRES_USER: user
  POSTGRES_DB: kutt
    


  
  