apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "kuttt-app.fullname" . }}-sts
  labels:
    {{- include "kuttt-app.labels" . | nindent 4 }}
spec:
  serviceName: kuttdb-svc
  selector:
    matchLabels:
      {{- include "kuttt-app.selectorLabels" . | nindent 6 }}
  replicas: {{ .Values.replicaCount }}
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        {{- include "kuttt-app.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - image: postgres:12-alpine
        name: postgres
        volumeMounts:
        - name: postgres-data
          mountPath: /data  
        env: 
        - name: POSTGRES_USER
          valueFrom:
           configMapKeyRef:
            name: kutt-config
            key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
           secretKeyRef:
            name: db-secret
            key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          valueFrom:
           configMapKeyRef:
            name: kutt-config
            key: POSTGRES_DB       
        ports:
        - containerPort: 5432
      - image: redis:6.0-alpine
        name: redis
        ports:
          - containerPort: 6379
        volumeMounts:
        - name: redis-data
          mountPath: /data
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
           claimName: kutt-pvc-pst
        - name: redis-data
          persistentVolumeClaim:
           claimName: kutt-pvc-red
