apiVersion: v1
kind: Service 
metadata: 
  name: postgres
  labels:
    {{- include "kuttt-app.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports: 
    - targetPort: 5432
      port: 5432
  selector:
    {{- include "kuttt-app.selectorLabels" . | nindent 4 }}