apiVersion: v1
kind: Service 
metadata: 
  name: redis 
  labels:
    {{- include "kuttt-app.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports: 
    - targetPort: 6379
      port: 6379
  selector:
    {{- include "kuttt-app.selectorLabels" . | nindent 4 }}