apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kuttt-app.fullname" . }}
  labels:
    {{- include "kuttt-app.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "kuttt-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "kuttt-app.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "kuttt-app.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          command: ["/bin/sh", "-c"]
          args:
          - ./wait-for-it.sh postgres:5432 -- npm start
          env:
          - name: DB_HOST
            valueFrom:
             configMapKeyRef:
              name: kutt-config
              key: DB_HOST
          - name: DB_NAME
            valueFrom:
             configMapKeyRef:
              name: kutt-config
              key: DB_NAME
          - name: DB_USER
            valueFrom:
             configMapKeyRef:
              name: kutt-config
              key: DB_USER
          - name: DB_PASSWORD
            valueFrom:
             configMapKeyRef:
              name: kutt-config
              key: DB_PASSWORD
          - name: REDIS_HOST
            valueFrom:
             configMapKeyRef:
              name: kutt-config
              key: REDIS_HOST     
          - name: REDIS_PORT
            valueFrom:
             configMapKeyRef:
              name: kutt-config
              key: REDIS_PORT     
          - name: JWT_SECRET
            valueFrom:
             configMapKeyRef:
              name: kutt-config
              key: JWT_SECRET  
          - name: MAIL_HOST
            valueFrom:
             configMapKeyRef:
              name: kutt-config
              key: MAIL_HOST  
          - name: MAIL_PORT
            valueFrom:
             configMapKeyRef:
              name: kutt-config
              key: MAIL_PORT  
          - name: MAIL_USER
            valueFrom:
             configMapKeyRef:
              name: kutt-config
              key: MAIL_USER  
          - name: MAIL_PASSWORD
            valueFrom:
             configMapKeyRef:
              name: kutt-config
              key: MAIL_PASSWORD  
          - name: SITE_NAME
            valueFrom:
             configMapKeyRef:
              name: kutt-config
              key: SITE_NAME
          - name: DEFAULT_DOMAIN
            valueFrom:
             configMapKeyRef:
              name: kutt-config
              key: DEFAULT_DOMAIN
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
