apiVersion: networking.k8s.io/v1
kind: Ingress 
metadata: 
  name: kutt-ing
  annotations:
    kubernetes.io/ingress.allow-http: "true"
  labels:
    app: kutt
spec: 
  ingressClassName: nginx
  defaultBackend:
    service:
      name: kutt-svc
      port:
        number: 3000
  rules:
  - host: kuttk8s.local
    http:
     paths:
     - path: /
       pathType: Prefix
       backend:
         service:
           name: kutt-svc
           port:
            number: 3000
        