grafana:
  enabled: true
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - grafana-dev.local
prometheus:
  enabled: true
  isDefault: false
  server:
    ingress:
      enabled: true
      ingressClassName: nginx
      hosts:
        - prometheus-dev.local